##
# .eslintrc.yml
#
# Created by Zander Otavka on 12/21/16.
# Copyright (C) 2016 Zander Otavka.  All rights reserved.
#
# Distributed under the GNU General Public License, Version 3.
# See the accompanying file LICENSE or http://www.gnu.org/licenses/gpl-3.0.txt
##

installedESLint: true
parserOptions:
  ecmaVersion: 2015
  sourceType: module
env:
  es6: true
  browser: true
globals:
  chrome: true

rules:
  # Code Quality
  eqeqeq:
    - error
    - always
  no-confusing-arrow:
    - error
    - allowParens: true
  no-constant-condition:
    - error
    - checkLoops: false
  no-undef:
    - error
  no-unused-vars:
    - warn
    - args: none
  no-lonely-if:
    - error
  no-console:
    - warn
    - allow:
        - assert
        - error
  no-underscore-dangle:
    - error
    - allowAfterThis: true
      allowAfterSuper: true
  no-param-reassign:
    - error
    - props: false
  no-plusplus:
    - off
  no-else-return:
    - off
  class-methods-use-this:
    - off

  # Code Style
  camelcase:
    - warn
    - properties: always
  curly:
    - warn
    - all
  arrow-body-style:
    - warn
    - as-needed
  max-len:
    - off
  indent:
    - off
  new-parens:
    - off
  space-in-parens:
    - off
  object-curly-spacing:
    - off
  arrow-parens:
    - off
  comma-dangle:
    - off
  no-multiple-empty-lines:
    - off
